config/routes.rb
Rails.application.routes.draw do
  resources :portfolios
  
  get "/some/*missing", to: "missings#index"

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root "pages#home"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0, published: 1}
    extend FriendlyId
    friendly_id :title, use: :slugged
    
    validates :title, presence: true
    validates :body, presence: true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

    validates :title, :body, :main_image, :thumb_image

end

app/models/skill.rb
class Skill < ApplicationRecord

    validates :title, :percent_utilized

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def toggle_status
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    redirect_to blogs_url, notice: "Post!"
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/missings_controller.rb
class MissingsController < ApplicationController

def index
    
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
  
 
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    def index
        @portfolio_items = Portfolio.all
    end
    
    def show
        @portfolio_item = Portfolio.find(params[:id]) 

    end
    
    def new
        @portfolio_item = Portfolio.new
    end
    
    def edit
       @portfolio_item = Portfolio.find(params[:id]) 
    end
    
    def create
       @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body))
       respond_to do |format|
           if @portfolio_item.save
            format.html { redirect_to portfolios_path, notice: 'Portfolio has been created'} 
           else
               format.html{ render :new}
           end
       end
    end
    
    def update
        @portfolio_item = Portfolio.find(params[:id])
       respond_to do |format|
          if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body)) 
             format.html { redirect_to portfolios_path, notice: "Portfolio has been updated"}
          else
             format.html {render :new}
          end
       end
    end
    
    def destroy
        @portfolio_item = Portfolio.find(params[:id])
        
        respond_to do |format|
           if @portfolio_item.destroy
                format.html{redirect_to portfolios_path, notice: "Portfolio has been destroyed."}
           else
                format.html{redirect_to portfolio_path, alert:"Portfolio couldn't been destroyed"}
           end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevCampPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/missings/index.html.erb
<h2>You missed something</h2>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h2>Blog Posts</h2>
<%= @posts.inspect %>

<br /><br/>
<h2>Skills</h2>
<%= @skills.inspect %>

app/views/portfolios/edit.html.erb
<h2>Edit Portfolio</h2>
<%= form_for(@portfolio_item) do |f| %>
<p>
    <%= f.label :title %>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
</p>
<p>
    <%= f.label :body %>
    <%= f.text_field :body %>
</p>
<p>
    <%= f.submit %>
</p>

<%end%>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>
<%= link_to "Create new Portfolio", new_portfolio_path %>
<%= @portfolio_items.each do |portfolio_item| %>
 <p><%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></p>
 <p><%= portfolio_item.subtitle %></p>
 <p><%= portfolio_item.body %></p>
 <p><%= image_tag portfolio_item.main_image unless portfolio_item.main_image.nil?  %></p>
 <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
 <p><%= portfolio_item.created_at %></p>
 <p><%= portfolio_item.updated_at %></p>
    <br />
    <p>
     <%= link_to "Edit", edit_portfolio_url(portfolio_item) %>
     <br />
     <%= button_to "Destroy", portfolio_path(portfolio_item), method: :delete %>
    </p>
    <br/>
    
<hr />
<% end %>

app/views/portfolios/new.html.erb
<h2>Create new Portfolio</h2>
<%= form_for(@portfolio_item) do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle %>
    </div>
    <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    <div class="field">
        <%= f.submit %>
    </div>
<% end %>

app/views/portfolios/show.html.erb
<h2><%= @portfolio_item.title %></h2>
 <p><%= @portfolio_item.subtitle %></p>
 <p><%= @portfolio_item.body %></p>
 <p><%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil?  %></p>
 <p><%= image_tag @portfolio_item.thumb_image unless @portfolio_item.thumb_image.nil? %></p>
 <p><%= @portfolio_item.created_at %></p>
 <p><%= @portfolio_item.updated_at %></p>
 
 <%= link_to "Back to All Posts", portfolios_path %>